#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Mar 31, 2018 10:42:03 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import test_support

def vp_start_gui(dataset):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = test (root,dataset)
    test_support.init(root, top,dataset)
    root.mainloop()

w = None
def create_test(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = test (w)
    test_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_test():
    global w
    w.destroy()
    w = None


class test:
    def __init__(self, top=None,dataMerge=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+650+150")
        top.title("test")
        top.configure(background="#d9d9d9")


        import TablaInterfaz as TI
        print (dataMerge.datos())
        self.tablaActual = TI.TablaInterfaz(top, dataMerge.nombresColumnas(), cantidadFilasVisibles= 20)
        self.tablaActual.place(x=10, y=150, anchoPix= 960)
        self.tablaActual.cargarDataset(dataMerge)





if __name__ == '__main__':
    import pandas as pd
    import numpy as np
    import Dataset as ds
    df2 = pd.DataFrame({ 'A' : 1.,
                       'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                       'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                      'F' : 'foo' })
    import numpy as np
    df=ds.Dataset()
    df.cargarDataframe(pd.DataFrame([[np.nan, 2, np.nan, 0], [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5]],
                  columns=list('ABCD')))
    print(df.datos())
    vp_start_gui(df)



